### ISSUE TITLE
An example, how to read from `stylesheet.statements`

### ISSUE THREAD

**Issue by sems** [stackotter/swift-css-parser#2]
As the title states. It would be nice to have an example somewhere which states how to access the `statements` since they are as the enumeration `Statement`. Lots of people are not used to accessing properties by enum.

**Comment by stackotter** [comment]
Thanks for the feedback!

As an example, here's how I would iterate through all regular `background` rules (ignoring media queries) in a document:

```swift
for statement in stylesheet.statements {
  switch statement {
    case .ruleSet(let ruleSet):
      var background: String?
      for declaration in ruleSet.declarations where declaration.property == "background" {
        if declaration.property == "background" {
          background = declaration.value
          break
        }
      }
      if let background = background {
        print("background for '\(ruleSet.selector)' is '\(background)'")
      }
    default:
      break
  }
}
```

If that answers your question about how to access properties, then I will add it to the readme.

**Comment by sems** [comment]
Great, this is a great example, it would be clear!

**Comment by stackotter** [comment]
Sorry for taking so long to get around to this issue, I've been pretty busy. Hopefully the new readme example helps :)
